[32m2024-02-08 15:07:21 +0800[0m - dagster - [34mDEBUG[0m - refresh_forecast_model_job - 1278e48e-9107-4ffd-a359-19cba869c2c3 - 14859 - LOGS_CAPTURED - Started capturing logs in process (pid: 14859).
[32m2024-02-08 15:07:21 +0800[0m - dagster - [34mDEBUG[0m - refresh_forecast_model_job - 1278e48e-9107-4ffd-a359-19cba869c2c3 - 14859 - dbt_project_assets - STEP_START - Started execution of step "dbt_project_assets".
[32m2024-02-08 15:07:21 +0800[0m - dagster - [34mINFO[0m - refresh_forecast_model_job - 1278e48e-9107-4ffd-a359-19cba869c2c3 - dbt_project_assets - A dbt subsetted execution is being performed. Overriding default dbt selection arguments `['--select', 'fqn:*']` with arguments: `['--select', 'fqn:dbt_project.cleaned.users_cleaned fqn:dbt_project.analytics.order_stats fqn:dbt_project.analytics.orders_augmented fqn:dbt_project.cleaned.orders_cleaned fqn:dbt_project.analytics.daily_order_summary']`
[32m2024-02-08 15:07:21 +0800[0m - dagster - [34mINFO[0m - refresh_forecast_model_job - 1278e48e-9107-4ffd-a359-19cba869c2c3 - dbt_project_assets - Copying `/Volumes/workspace/data/dbt-dagster-poetry/dbt_project/target/partial_parse.msgpack` to `/Volumes/workspace/data/dbt-dagster-poetry/dbt_project/target/dbt_project_assets-1278e48-5157f97/partial_parse.msgpack` to take advantage of partial parsing.
[32m2024-02-08 15:07:21 +0800[0m - dagster - [34mINFO[0m - refresh_forecast_model_job - 1278e48e-9107-4ffd-a359-19cba869c2c3 - dbt_project_assets - Running dbt command: `dbt build --select fqn:dbt_project.cleaned.users_cleaned fqn:dbt_project.analytics.order_stats fqn:dbt_project.analytics.orders_augmented fqn:dbt_project.cleaned.orders_cleaned fqn:dbt_project.analytics.daily_order_summary`.
[32m2024-02-08 15:07:22 +0800[0m - dagster - [34mINFO[0m - refresh_forecast_model_job - 1278e48e-9107-4ffd-a359-19cba869c2c3 - dbt_project_assets - Finished dbt command: `dbt build --select fqn:dbt_project.cleaned.users_cleaned fqn:dbt_project.analytics.order_stats fqn:dbt_project.analytics.orders_augmented fqn:dbt_project.cleaned.orders_cleaned fqn:dbt_project.analytics.daily_order_summary`.
[32m2024-02-08 15:07:22 +0800[0m - dagster - [34mERROR[0m - [31mrefresh_forecast_model_job - 1278e48e-9107-4ffd-a359-19cba869c2c3 - 14859 - dbt_project_assets - STEP_FAILURE - Execution of step "dbt_project_assets" failed.

dagster_dbt.errors.DagsterDbtCliRuntimeError: The dbt CLI process with command `dbt build --select fqn:dbt_project.cleaned.users_cleaned fqn:dbt_project.analytics.order_stats fqn:dbt_project.analytics.orders_augmented fqn:dbt_project.cleaned.orders_cleaned fqn:dbt_project.analytics.daily_order_summary` failed with exit code 1. Check the stdout in the Dagster compute logs for the full information about the error, or view the dbt debug log: /Volumes/workspace/data/dbt-dagster-poetry/dbt_project/target/dbt_project_assets-1278e48-5157f97/dbt.log.

Errors parsed from dbt logs:
2 of 5 ERROR creating sql table model dbt_alice.users_cleaned .................. [[31mERROR[0m in 0.05s]
1 of 5 ERROR creating sql table model dbt_alice.orders_cleaned ................. [[31mERROR[0m in 0.05s]
  Database Error in model users_cleaned (models/cleaned/users_cleaned.sql)
  relation "raw_data.users" does not exist
  LINE 15: from "dbt"."raw_data"."users"
                ^
  compiled Code at target/dbt_project_assets-1278e48-5157f97/run/dbt_project/models/cleaned/users_cleaned.sql
  Database Error in model orders_cleaned (models/cleaned/orders_cleaned.sql)
  relation "raw_data.orders" does not exist
  LINE 20: from "dbt"."raw_data"."orders"
                ^
  compiled Code at target/dbt_project_assets-1278e48-5157f97/run/dbt_project/models/cleaned/orders_cleaned.sql

Stack Trace:
  File "/Volumes/workspace/data/dbt-dagster-poetry/.venv/lib/python3.11/site-packages/dagster/_core/execution/plan/execute_plan.py", line 286, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/Volumes/workspace/data/dbt-dagster-poetry/.venv/lib/python3.11/site-packages/dagster/_core/execution/plan/execute_step.py", line 487, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/Volumes/workspace/data/dbt-dagster-poetry/.venv/lib/python3.11/site-packages/dagster/_core/execution/plan/execute_step.py", line 169, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/Volumes/workspace/data/dbt-dagster-poetry/.venv/lib/python3.11/site-packages/dagster/_core/execution/plan/execute_step.py", line 95, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/Volumes/workspace/data/dbt-dagster-poetry/.venv/lib/python3.11/site-packages/dagster/_core/execution/plan/compute.py", line 212, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/Volumes/workspace/data/dbt-dagster-poetry/.venv/lib/python3.11/site-packages/dagster/_core/execution/plan/compute.py", line 181, in _yield_compute_results
    for event in iterate_with_context(
  File "/Volumes/workspace/data/dbt-dagster-poetry/.venv/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 467, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Volumes/workspace/data/dbt-dagster-poetry/dagster_project/assets/dbt/__init__.py", line 36, in dbt_project_assets
    yield from dbt.cli(["build"], context=context).stream()
  File "/Volumes/workspace/data/dbt-dagster-poetry/.venv/lib/python3.11/site-packages/dagster_dbt/core/resources_v2.py", line 388, in stream
    for event in self.stream_raw_events():
  File "/Volumes/workspace/data/dbt-dagster-poetry/.venv/lib/python3.11/site-packages/dagster_dbt/core/resources_v2.py", line 425, in stream_raw_events
    self._raise_on_error()
  File "/Volumes/workspace/data/dbt-dagster-poetry/.venv/lib/python3.11/site-packages/dagster_dbt/core/resources_v2.py", line 499, in _raise_on_error
    raise DagsterDbtCliRuntimeError(
[0m
